# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('body', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=256, null=True)),
                ('quote', models.CharField(blank=True, max_length=256, null=True)),
                ('primary_color', models.CharField(default='#595299', max_length=8)),
                ('text_color', models.CharField(default='#4C4C4C', max_length=8)),
                ('secondary_text_color', models.CharField(default='#FFFFFF', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PageIconBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.Page')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PageImageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.ImageBlock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.Page')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PageSimpleBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.Page')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SimpleBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IconBlock',
            fields=[
                ('simpleblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splash.SimpleBlock')),
                ('icon', models.CharField(max_length=32)),
            ],
            bases=('splash.simpleblock',),
        ),
        migrations.AddField(
            model_name='pagesimpleblock',
            name='simple_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.SimpleBlock'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_blocks',
            field=models.ManyToManyField(related_name='image_blocks', through='splash.PageImageBlock', to='splash.ImageBlock'),
        ),
        migrations.AddField(
            model_name='page',
            name='simple_blocks',
            field=models.ManyToManyField(related_name='simple_blocks', through='splash.PageSimpleBlock', to='splash.SimpleBlock'),
        ),
        migrations.AddField(
            model_name='pageiconblock',
            name='icon_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.IconBlock'),
        ),
        migrations.AddField(
            model_name='page',
            name='icon_blocks',
            field=models.ManyToManyField(related_name='icon_blocks', through='splash.PageIconBlock', to='splash.IconBlock'),
        ),
    ]
