# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('body', tinymce.models.HTMLField()),
                ('icon', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='imageblock',
            name='code',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='frissan', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='primary_color',
            field=models.CharField(default='#595299', max_length=8),
        ),
        migrations.AddField(
            model_name='page',
            name='quote',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='secondary_text_color',
            field=models.CharField(default='#FFFFFF', max_length=8),
        ),
        migrations.AddField(
            model_name='page',
            name='text_color',
            field=models.CharField(default='#4C4C4C', max_length=8),
        ),
        migrations.AlterField(
            model_name='page',
            name='tagline',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
