# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageiconblock',
            old_name='icon_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='pageimageblock',
            old_name='image_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='pagesimpleblock',
            old_name='simple_block',
            new_name='block',
        ),
    ]
