# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_auto_20160324_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ga',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
