# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_auto_20160323_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon_blocks',
            field=models.ManyToManyField(to='splash.IconBlock'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_blocks',
            field=models.ManyToManyField(to='splash.ImageBlock'),
        ),
        migrations.AddField(
            model_name='page',
            name='simple_blocks',
            field=models.ManyToManyField(to='splash.SimpleBlock'),
        ),
    ]
