# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0005_auto_20160324_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconblock',
            name='body',
        ),
        migrations.RemoveField(
            model_name='iconblock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='iconblock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='iconblock',
            name='title',
        ),
        migrations.AddField(
            model_name='iconblock',
            name='simpleblock_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='splash.SimpleBlock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='icon_blocks',
            field=models.ManyToManyField(related_name='icon_blocks', to='splash.IconBlock'),
        ),
    ]
